title:                Sash Zats
tagline:              ''
description:          'Swift & Objective-C. iOS & OS X.'
url:                  http://blog.zats.io
name:                 Sash Zats

author:
  name:               Sash Zats
  url:                https://zats.io

version:              1.0.0

github:
  repo:               https://github.com/zats

paginate:             5

markdown:            kramdown
redcarpet:
  extensions:        ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "footnotes", "tables", "with_toc_data"]

excerpt_separator:    <excerpt/>
permalink:            pretty
